In [4]:
import pandas as pd
import numpy as np 
import matplotlib.pyplot as plt
import seaborn as sns
import warnings
warnings.filterwarnings('ignore')

print ("all libraries loaded sucessfuly")

all libraries loaded sucessfuly

In [9]:
df = pd.read_csv('../data/raw/telco-Customer-Churn.csv')
print(f"Dataset shape: {df.shape}")
print(f"Total Customers: {df.shape[0]}")
print(f"Total Features: {df.shape[1]}")

Dataset shape: (7043, 21)
Total Customers: 7043
Total Features: 21

In [10]:
df.head(10)

,customerID,gender,SeniorCitizen,Partner,Dependents,tenure,PhoneService,MultipleLines,InternetService,OnlineSecurity,...,DeviceProtection,TechSupport,StreamingTV,StreamingMovies,Contract,PaperlessBilling,PaymentMethod,MonthlyCharges,TotalCharges,Churn
0,7590-VHVEG,Female,0,Yes,No,1,No,No phone service,DSL,No,...,No,No,No,No,Month-to-month,Yes,Electronic check,29.85,29.85,No
1,5575-GNVDE,Male,0,No,No,34,Yes,No,DSL,Yes,...,Yes,No,No,No,One year,No,Mailed check,56.95,1889.5,No
2,3668-QPYBK,Male,0,No,No,2,Yes,No,DSL,Yes,...,No,No,No,No,Month-to-month,Yes,Mailed check,53.85,108.15,Yes
3,7795-CFOCW,Male,0,No,No,45,No,No phone service,DSL,Yes,...,Yes,Yes,No,No,One year,No,Bank transfer (automatic),42.30,1840.75,No
4,9237-HQITU,Female,0,No,No,2,Yes,No,Fiber optic,No,...,No,No,No,No,Month-to-month,Yes,Electronic check,70.70,151.65,Yes
5,9305-CDSKC,Female,0,No,No,8,Yes,Yes,Fiber optic,No,...,Yes,No,Yes,Yes,Month-to-month,Yes,Electronic check,99.65,820.5,Yes
6,1452-KIOVK,Male,0,No,Yes,22,Yes,Yes,Fiber optic,No,...,No,No,Yes,No,Month-to-month,Yes,Credit card (automatic),89.10,1949.4,No
7,6713-OKOMC,Female,0,No,No,10,No,No phone service,DSL,Yes,...,No,No,No,No,Month-to-month,No,Mailed check,29.75,301.9,No
8,7892-POOKP,Female,0,Yes,No,28,Yes,Yes,Fiber optic,No,...,Yes,Yes,Yes,Yes,Month-to-month,Yes,Electronic check,104.80,3046.05,Yes
9,6388-TABGU,Male,0,No,Yes,62,Yes,No,DSL,Yes,...,No,No,No,No,One year,No,Bank transfer (automatic),56.15,3487.95,No

In [11]:
print("=== COLUMN INFO ===\n")
print(df.dtypes)

=== COLUMN INFO ===

customerID              str
gender                  str
SeniorCitizen         int64
Partner                 str
Dependents              str
tenure                int64
PhoneService            str
MultipleLines           str
InternetService         str
OnlineSecurity          str
OnlineBackup            str
DeviceProtection        str
TechSupport             str
StreamingTV             str
StreamingMovies         str
Contract                str
PaperlessBilling        str
PaymentMethod           str
MonthlyCharges      float64
TotalCharges            str
Churn                   str
dtype: object

In [12]:
churn_counts = df['Churn'].value_counts()
churn_pct = df['Churn'].value_counts(normalize=True) * 100

print("=== CHURN DISTRIBUTION ===")
print(f"Not Churned : {churn_counts['No']}  ({churn_pct['No']:.1f}%)")
print(f"Churned     : {churn_counts['Yes']} ({churn_pct['Yes']:.1f}%)")
print(f"\nThis means {churn_pct['Yes']:.1f}% of customers left the company.")
print(f"That is your core business problem.")

=== CHURN DISTRIBUTION ===
Not Churned : 5174  (73.5%)
Churned     : 1869 (26.5%)

This means 26.5% of customers left the company.
That is your core business problem.

In [13]:
print("=== MISSING VALUES ===\n")
missing = df.isnull().sum()
missing_pct = (df.isnull().sum() / len(df)) * 100

missing_df = pd.DataFrame({
    'Missing Count': missing,
    'Missing %': missing_pct
})

print(missing_df[missing_df['Missing Count'] > 0])
print("\nColumns with zero missing values — clean ✓" if missing.sum() == 0 else "")

=== MISSING VALUES ===

Empty DataFrame
Columns: [Missing Count, Missing %]
Index: []

Columns with zero missing values — clean ✓

In [14]:
print("=== NUMERICAL COLUMNS SUMMARY ===\n")
df.describe()

=== NUMERICAL COLUMNS SUMMARY ===

       SeniorCitizen       tenure  MonthlyCharges
count    7043.000000  7043.000000     7043.000000
mean        0.162147    32.371149       64.761692
std         0.368612    24.559481       30.090047
min         0.000000     0.000000       18.250000
25%         0.000000     9.000000       35.500000
50%         0.000000    29.000000       70.350000
75%         0.000000    55.000000       89.850000
max         1.000000    72.000000      118.750000

In [15]:
duplicates = df['customerID'].duplicated().sum()
print(f"Duplicate Customer IDs: {duplicates}")

if duplicates == 0:
    print("No duplicates found — each row is a unique customer ✓")
else:
    print(f"WARNING: {duplicates} duplicate IDs found — needs cleaning!")

Duplicate Customer IDs: 0
No duplicates found — each row is a unique customer ✓

In [16]:
print("=== UNIQUE VALUE COUNTS PER COLUMN ===\n")
for col in df.columns:
    print(f"{col:25s} → {df[col].nunique()} unique values")

=== UNIQUE VALUE COUNTS PER COLUMN ===

customerID                → 7043 unique values
gender                    → 2 unique values
SeniorCitizen             → 2 unique values
Partner                   → 2 unique values
Dependents                → 2 unique values
tenure                    → 73 unique values
PhoneService              → 2 unique values
MultipleLines             → 3 unique values
InternetService           → 3 unique values
OnlineSecurity            → 3 unique values
OnlineBackup              → 3 unique values
DeviceProtection          → 3 unique values
TechSupport               → 3 unique values
StreamingTV               → 3 unique values
StreamingMovies           → 3 unique values
Contract                  → 3 unique values
PaperlessBilling          → 2 unique values
PaymentMethod             → 4 unique values
MonthlyCharges            → 1585 unique values
TotalCharges              → 6531 unique values
Churn                     → 2 unique values

In [17]:
summary = {
    'total_rows': df.shape[0],
    'total_columns': df.shape[1],
    'churn_rate_%': round(churn_pct['Yes'], 2),
    'missing_values': int(df.isnull().sum().sum()),
    'duplicate_ids': int(duplicates)
}

print("=== PROJECT DATA PROFILE SUMMARY ===\n")
for key, value in summary.items():
    print(f"  {key:25s}: {value}")

=== PROJECT DATA PROFILE SUMMARY ===

  total_rows               : 7043
  total_columns            : 21
  churn_rate_%             : 26.54
  missing_values           : 0
  duplicate_ids            : 0